=== alexandergillon/mini-metro-maps/docs/network-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Network-Schema",
    "description": "JSON schema for Mini Metro Maps networks",
    "type": "object",
    "properties": {
        "lineWidth": {
            "description": "Line width of a metro line, in pixels",
            "type": "integer"
        },
        "maxX": {
            "description": "Maximum scroll in the X direction",
            "type": "integer"
        },
        "maxY": {
            "description": "Maximum scroll in the Y direction",
            "type": "integer"
        },
        "metroLines": {
            "description": "Data describing the metro lines",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Metro line name",
                        "type": "string"
                    },
                    "color": {
                        "description": "Metro line color",
                        "type": "string",
                        "pattern": "^#[0-9a-fA-F]{6}$"
                    },
                    "stations": {
                        "description": "Data describing the stations on the metro line",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "description": "Station identifier - must be unique across all lines/stations",
                                    "type": "string"
                                },
                                "name": {
                                    "description": "Human-readable station name",
                                    "type": "string"
                                },
                                "x": {
                                    "description": "X coordinate",
                                    "type": "integer"
                                },
                                "y": {
                                    "description": "Y coordinate",
                                    "type": "integer"
                                }
                            },
                            "required": ["id", "name", "x", "y"]
                        }
                    },
                    "edges": {
                        "description": "Data describing edges between stations",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "station1Id": {
                                    "description": "Identifier of first station in edge",
                                    "type": "string"
                                },
                                "station2Id": {
                                    "description": "Identifier of second station in edge",
                                    "type": "string"
                                },
                                "lineSegments": {
                                    "description": "Data describing line segments which make up edge",
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "p0": {
                                                "description": "First point of line segment",
                                                "type": "object",
                                                "properties": {
                                                    "x": {
                                                        "description": "X coordinate",
                                                        "type": "integer"
                                                    },
                                                    "y": {
                                                        "description": "Y coordinate",
                                                        "type": "integer"
                                                    }
                                                },
                                                "required": ["x", "y"]
                                            },
                                            "p1": {
                                                "description": "Second point of line segment",
                                                "$ref": "#/properties/metroLines/items/properties/edges/items/properties/lineSegments/items/properties/p0"
                                            },
                                            "p2": {
                                                "description": "Third point of line segment",
                                                "type": ["object", "null"],
                                                "properties": {
                                                    "x": {
                                                        "description": "X coordinate",
                                                        "type": "integer"
                                                    },
                                                    "y": {
                                                        "description": "Y coordinate",
                                                        "type": "integer"
                                                    }
                                                },
                                                "required": ["x", "y"]
                                            },
                                            "p3": {
                                                "description": "Fourth point of line segment",
                                                "$ref": "#/properties/metroLines/items/properties/edges/items/properties/lineSegments/items/properties/p2"
                                            },
                                            "straightLine": {
                                                "description": "Whether line segment is a straight line. If true, this segment is a straight line from p0 to p1. If false, this segment is a cubic Bezier curve with control points p0, p1, p2, p3.",
                                                "type": "boolean"
                                            }
                                        },
                                        "required": ["p0", "p1", "p2", "p3", "straightLine"]
                                    }
                                }
                            },
                            "required": ["station1Id", "station2Id", "lineSegments"]
                        }
                    },
                    "endpointLineSegments": {
                        "description": "Data for end of line markers",
                        "type": "array",
                        "items": {
                            "$ref": "#/properties/metroLines/items/properties/edges/items/properties/lineSegments/items"
                        }
                    },
                    "zIndex": {
                        "description": "Z-index for drawing the metro line",
                        "type": "integer"
                    }
                },
                "required": ["name", "color", "stations", "edges", "endpointLineSegments", "zIndex"]
            }
        }
    },
    "required": ["lineWidth", "maxX", "maxY", "metroLines"]
}

=== alexandergillon/mini-metro-maps/docs/maps/london/london.json
{"lineWidth":50,"maxX":16807,"maxY":11934,"metroLines":[{"name":"hammersmith-city","color":"#ec9bad","stations":[{"id":"hammersmithcity_940GZZLUKSX","name":"King's Cross St. Pancras","x":8999,"y":4696},{"id":"hammersmithcity_940GZZLUMED","name":"Mile End","x":12515,"y":5025},{"id":"hammersmithcity_940GZZLUBBB","name":"Bromley-by-Bow","x":13455,"y":5025},{"id":"hammersmithcity_940GZZLUFCN","name":"Farringdon","x":9412,"y":4996},{"id":"hammersmithcity_940GZZLULAD","name":"Ladbroke Grove","x":4713,"y":5540},{"id":"hammersmithcity_940GZZLUESQ","name":"Euston Square","x":8125,"y":4696},{"id":"hammersmithcity_940GZZLUADE","name":"Aldgate East","x":11356,"y":5581},{"id":"hammersmithcity_940GZZLUERC","name":"Edgware Road (Circle Line)","x":6140,"y":4696},{"id":"hammersmithcity_940GZZLUPLW","name":"Plaistow","x":14146,"y":4933},{"id":"hammersmithcity_940GZZLUBKG","name":"Barking","x":14749,"y":4330},{"id":"hammersmithcity_940GZZLUWPL","name":"Whitechapel","x":11506,"y":5431},{"id":"hammersmithcity_940GZZLUGHK","name":"Goldhawk Road","x":4713,"y":6590},{"id":"hammersmithcity_940GZZLUMGT","name":"Moorgate","x":9936,"y":5448},{"id":"hammersmithcity_940GZZLUBST","name":"Baker Street","x":7274,"y":4696},{"id":"hammersmithcity_940GZZLULVT","name":"Liverpool Street","x":10286,"y":5448},{"id":"hammersmithcity_940GZZLUSGN","name":"Stepney Green","x":12145,"y":5025},{"id":"hammersmithcity_940GZZLURYO","name":"Royal Oak","x":4813,"y":5145},{"id":"hammersmithcity_940GZZLUSBM","name":"Shepherd's Bush Market","x":4713,"y":6403},{"id":"hammersmithcity_940GZZLUWHM","name":"West Ham","x":13759,"y":5025},{"id":"hammersmithcity_940GZZLUPAH","name":"Paddington (H&C Line)-Underground","x":5571,"y":4696},{"id":"hammersmithcity_940GZZLUEHM","name":"East Ham","x":14571,"y":4508},{"id":"hammersmithcity_940GZZLUBWR","name":"Bow Road","x":12963,"y":5025},{"id":"hammersmithcity_940GZZLUHSC","name":"Hammersmith (H&C Line)","x":4713,"y":6700},{"id":"hammersmithcity_940GZZLULRD","name":"Latimer Road","x":4713,"y":5700},{"id":"hammersmithcity_940GZZLUGPS","name":"Great Portland Street","x":7515,"y":4696},{"id":"hammersmithcity_940GZZLUWSP","name":"Westbourne Park","x":4713,"y":5390},{"id":"hammersmithcity_940GZZLUWLA","name":"Wood Lane","x":4713,"y":6165},{"id":"hammersmithcity_940GZZLUBBN","name":"Barbican","x":9701,"y":5285},{"id":"hammersmithcity_940GZZLUUPK","name":"Upton Park","x":14367,"y":4712}],"edges":[{"station1Id":"hammersmithcity_940GZZLUWSP","station2Id":"hammersmithcity_940GZZLURYO","lineSegments":[{"p0":{"x":4713,"y":5390},"p1":{"x":4713,"y":5345},"p2":null,"p3":null,"straightLine":true},{"p0":{"x":4713,"y":5345},"p1":{"x":4713,"y":5245},"p2":{"x":4713,"y":5245},"p3":{"x":4788,"y":5170},"straightLine":false},{"p0":{"x":4788,"y":5170},"p1":{"x":4813,"y":5145},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLURYO","station2Id":"hammersmithcity_940GZZLUPAH","lineSegments":[{"p0":{"x":5571,"y":4696},"p1":{"x":5362,"y":4696},"p2":null,"p3":null,"straightLine":true},{"p0":{"x":5362,"y":4696},"p1":{"x":5262,"y":4696},"p2":{"x":5262,"y":4696},"p3":{"x":5187,"y":4771},"straightLine":false},{"p0":{"x":5187,"y":4771},"p1":{"x":4813,"y":5145},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUKSX","station2Id":"hammersmithcity_940GZZLUFCN","lineSegments":[{"p0":{"x":8999,"y":4696},"p1":{"x":9012,"y":4696},"p2":null,"p3":null,"straightLine":true},{"p0":{"x":9012,"y":4696},"p1":{"x":9112,"y":4696},"p2":{"x":9112,"y":4696},"p3":{"x":9187,"y":4771},"straightLine":false},{"p0":{"x":9187,"y":4771},"p1":{"x":9412,"y":4996},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUBBN","station2Id":"hammersmithcity_940GZZLUMGT","lineSegments":[{"p0":{"x":9964,"y":5448},"p1":{"x":9864,"y":5448},"p2":{"x":9864,"y":5448},"p3":{"x":9789,"y":5373},"straightLine":false},{"p0":{"x":9789,"y":5373},"p1":{"x":9701,"y":5285},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLULVT","station2Id":"hammersmithcity_940GZZLUADE","lineSegments":[{"p0":{"x":10286,"y":5448},"p1":{"x":11356,"y":5581},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUWPL","station2Id":"hammersmithcity_940GZZLUSGN","lineSegments":[{"p0":{"x":12145,"y":5025},"p1":{"x":12012,"y":5025},"p2":null,"p3":null,"straightLine":true},{"p0":{"x":12012,"y":5025},"p1":{"x":11912,"y":5025},"p2":{"x":11912,"y":5025},"p3":{"x":11837,"y":5100},"straightLine":false},{"p0":{"x":11837,"y":5100},"p1":{"x":11506,"y":5431},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUWHM","station2Id":"hammersmithcity_940GZZLUPLW","lineSegments":[{"p0":{"x":13759,"y":5025},"p1":{"x":13954,"y":5025},"p2":null,"p3":null,"straightLine":true},{"p0":{"x":13954,"y":5025},"p1":{"x":14054,"y":5025},"p2":{"x":14054,"y":5025},"p3":{"x":14129,"y":4950},"straightLine":false},{"p0":{"x":14129,"y":4950},"p1":{"x":14146,"y":4933},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLULAD","station2Id":"hammersmithcity_940GZZLUWSP","lineSegments":[{"p0":{"x":4713,"y":5540},"p1":{"x":4713,"y":5390},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLULRD","station2Id":"hammersmithcity_940GZZLULAD","lineSegments":[{"p0":{"x":4713,"y":5700},"p1":{"x":4713,"y":5540},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUSGN","station2Id":"hammersmithcity_940GZZLUMED","lineSegments":[{"p0":{"x":12145,"y":5025},"p1":{"x":12515,"y":5025},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUWLA","station2Id":"hammersmithcity_940GZZLULRD","lineSegments":[{"p0":{"x":4713,"y":6165},"p1":{"x":4713,"y":5700},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUFCN","station2Id":"hammersmithcity_940GZZLUBBN","lineSegments":[{"p0":{"x":9412,"y":4996},"p1":{"x":9701,"y":5285},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUBWR","station2Id":"hammersmithcity_940GZZLUBBB","lineSegments":[{"p0":{"x":12963,"y":5025},"p1":{"x":13455,"y":5025},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUUPK","station2Id":"hammersmithcity_940GZZLUEHM","lineSegments":[{"p0":{"x":14367,"y":4712},"p1":{"x":14571,"y":4508},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUEHM","station2Id":"hammersmithcity_940GZZLUBKG","lineSegments":[{"p0":{"x":14571,"y":4508},"p1":{"x":14749,"y":4330},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUESQ","station2Id":"hammersmithcity_940GZZLUKSX","lineSegments":[{"p0":{"x":8125,"y":4696},"p1":{"x":8999,"y":4696},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUERC","station2Id":"hammersmithcity_940GZZLUBST","lineSegments":[{"p0":{"x":6140,"y":4696},"p1":{"x":7274,"y":4696},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUPAH","station2Id":"hammersmithcity_940GZZLUERC","lineSegments":[{"p0":{"x":5571,"y":4696},"p1":{"x":6140,"y":4696},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUGPS","station2Id":"hammersmithcity_940GZZLUESQ","lineSegments":[{"p0":{"x":7515,"y":4696},"p1":{"x":8125,"y":4696},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUADE","station2Id":"hammersmithcity_940GZZLUWPL","lineSegments":[{"p0":{"x":11356,"y":5581},"p1":{"x":11506,"y":5431},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUBST","station2Id":"hammersmithcity_940GZZLUGPS","lineSegments":[{"p0":{"x":7274,"y":4696},"p1":{"x":7515,"y":4696},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUMED","station2Id":"hammersmithcity_940GZZLUBWR","lineSegments":[{"p0":{"x":12515,"y":5025},"p1":{"x":12963,"y":5025},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUPLW","station2Id":"hammersmithcity_940GZZLUUPK","lineSegments":[{"p0":{"x":14146,"y":4933},"p1":{"x":14367,"y":4712},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUHSC","station2Id":"hammersmithcity_940GZZLUGHK","lineSegments":[{"p0":{"x":4713,"y":6700},"p1":{"x":4713,"y":6590},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUSBM","station2Id":"hammersmithcity_940GZZLUWLA","lineSegments":[{"p0":{"x":4713,"y":6403},"p1":{"x":4713,"y":6165},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUGHK","station2Id":"hammersmithcity_940GZZLUSBM","lineSegments":[{"p0":{"x":4713,"y":6590},"p1":{"x":4713,"y":6403},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUMGT","station2Id":"hammersmithcity_940GZZLULVT","lineSegments":[{"p0":{"x":9936,"y":5448},"p1":{"x":10286,"y":5448},"p2":null,"p3":null,"straightLine":true}]},{"station1Id":"hammersmithcity_940GZZLUBBB","station2Id":"hammersmithcity_940GZZLUWHM","lineSegments":[{"p0":{"x":13455,"y":5025},"p1":{"x":13759,"y":5025},"p2":null,"p3":null,"straightLine":true}]}],"endpointLineSegments":[{"p0":{"x":4638,"y":6700},"p1":{"x":4737,"y":6700},"p2":null,"p3":null,"straightLine":true},{"p0":{"x":14696,"y":4277},"p1":{"x":14783,"y":4364},"p2":null,"p3":null,"straightLine":true}],"zIndex":8},{"name":"victoria","color":"#00a0df","stations":[{"id":"victoria_940GZZLUKSX","name":"King's Cross St. Pancras","x":9115,"y":4630},{"id":"victoria_940GZZLUWWL","name":"Walthamstow Central","x":12730,"y":2681},{"id":"victoria_940GZZLUHAI","name":"Highbury & Islington","x":10470,"y":3755},{"id":"victoria_940GZZLUOXC","name":"Oxford Circus","x":7586,"y":5649},{"id":"victoria_940GZZLUSVS","name":"Seven Sisters","x":11380,"y":2681},{"id":"victoria_940GZZLUGPK","name":"Green Park","x":7227,"y":6224},{"id":"victoria_940GZZLUVIC","name":"Victoria","x":7227,"y":7047},{"id":"victoria_940GZZLUBLR","name":"Blackhorse
